### ISSUE TITLE
SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL

### ISSUE THREAD

**Issue by alihusnainarshad** [domainreseller/whmcs-dna#10]
I'm seeing the following error on my whmcs Version: 8.6.1

SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://whmcs.domainnameapi.com/DomainApi.svc?singlewsdl' : failed to load external entity "https://whmcs.domainnameapi.com/DomainApi.svc?singlewsdl"
in /whmcs/modules/registrars/domainnameapi/lib/dna.php:31
Stack trace:
#0 /whmcs/modules/registrars/domainnameapi/lib/dna.php(31): SoapClient->__construct()
#1 /whmcs/modules/registrars/domainnameapi/domainnameapi.php(44): DomainNameApi\DomainNameAPI_PHPLibrary->__construct()
#2 [internal function]: domainnameapi_getConfigArray()
#3 /whmcs/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func()
#4 /whmcs/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\Module\AbstractModule->call()
#5 /whmcs/admin/configregistrars.php(0): WHMCS\Module\Registrar->call()
#6 {main}

**Comment by bakcay** [comment]
Hello,
can you share "curl -vvv https://whmcs.domainnameapi.com/DomainApi.svc" output?

**Comment by alihusnainarshad** [comment]
Hi @bakcay 

Thanks for reply


b******@portal:~$ curl -vvv https://whmcs.domainnameapi.com/DomainApi.svc
*   Trying 2606:4700:3037::6815:6011:443...
* TCP_NODELAY set
* Connected to whmcs.domainnameapi.com (2606:4700:3037::6815:6011) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.domainnameapi.com
*  start date: Jan 20 14:51:54 2023 GMT
*  expire date: Apr 20 14:51:53 2023 GMT
*  subjectAltName: host "whmcs.domainnameapi.com" matched cert's "*.domainnameapi.com"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1P5
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x555bad44bb30)
> GET /DomainApi.svc HTTP/2
> Host: whmcs.domainnameapi.com
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 403 
< date: Tue, 28 Feb 2023 09:53:03 GMT
< content-type: text/html; charset=UTF-8
< permissions-policy: accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()
< referrer-policy: same-origin
< x-frame-options: SAMEORIGIN
< cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< expires: Thu, 01 Jan 1970 00:00:01 GMT
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=ZEdu6cyxWhe81piBF3PQkSdXAfK64kQvQ9V8WQZ8JaCTjFPEpLzWyPfHS6fEV%2Ft%2BsMJ37WAsExMk6seRUTrz%2B5omGBVsH9YwwcSWdFkKKVzkdZ8NTUB4T0QD8VHVkr8pfM1ydPHoSN%2BALKKElR3rE2qNpw4YWw%3D%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 7a08455e8f94d943-HEL
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
< 
<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
    

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <h1 class="zone-name-title h1">
            <img class="heading-favicon" src="/favicon.ico" alt="Icon for whmcs.domainnameapi.com"
                 onerror="this.onerror=null;this.parentNode.removeChild(this)">
            whmcs.domainnameapi.com
        </h1>
        <h2 class="h2" id="challenge-running">
            Checking if the site connection is secure
        </h2>
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/managed/nojs/transparent.gif?ray=7a08455e8f94d943')"></div>
        <div id="challenge-body-text" class="core-msg spacer">
            whmcs.domainnameapi.com needs to review the security of your connection before proceeding.
        </div>
        <form id="challenge-form" action="/DomainApi.svc?__cf_chl_f_tk=K_Tz4ugFY7fgg4N1w48OjuGaMfp3TpcSGJD6pziIrSI-1677577983-0-gaNycGzNCOU" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="w6TsmsPcc2.Xu5YJdUFXQ0kxdSmgxDdpXuyQkocUcUQ-1677577983-0-AYNHnisYc3IbTXiXOG2cd6QTQjiDpwv00rVnUhzPJtNYmNFhGHOVdpPU6xPXr4H1mPibHh8wOuLEZCWw7tVsh9-DUI1RwQV-zAOQmtgqqCKmASIK70GSCk8PcNDODRMJw2Ie0kgFuKQZQ2nG3RIpbRW7ZseXSbKj9iMevMsnSqqd58ia2zBxX7bC79CiVZdOm3zQ5zdTDxulvUWc3EDRjEcvCA7MyCmUPsks0SOsv6EfB29trBrm2BG22uGSSa7_OspUopr-i1Pi86ECX7tqOGqphXdCu296VzsvtEc1UFHkyDBdrwwpFY-cabVsjDf6Jwf973nLJNc6tr0NO1CYNF9of_kFRp_iqxc4DuF6qlRFqNwLHlBjq8B9_Q2IxfXBXpJ10JwYXgA-uOLCMhg-4r_ASEKJhGLk58PStpXhss_Vua_ZtrVwZJ0ZOVlEF3-p_xxhxbTZmoVhwlQM4KbJFp9CAiNR8ThVteLgPe7-tlrxUITQVhUGje05ZSy1DkYlw85X9ZJw_2gObTXKnwCx4DQOAnb-8zpcNJJ0Z3ok08CedjE-fG-O7atTEJ5zFiLfAQR6N-GvE7I_yji3r4mf9nyCP3qNmt5UvryFN78UdwlfxQ_7d7KJ8kGRCVyC21BjSNoUChQR6KK4e5eCSx_wY9xTZkhXwb0IqWMmediF79C-nApFgEGqcfVUGkovw2IQm5EpfEi9EqxYZIDo_XLJqBrMdhVu23erJxSARZ1PnbdeCT-s21MO6r6V-xPym19jppIcUOKdn5pQOLS6dVFpDf6gleiOxMbOpQZBRBSAVGKN13nj6gtEAF2wDLAaw29GNXdd4lAhjXFauDpydQkitSFjUXz7GjHMgcxU4QiiK8iBAlMT7yOrP2-C7tg0ePxWEs8PMCDxhhQBUnWH0U2kYIjeQ5rBAAaWfAiN-JJeVeIvkfYsAxec939HsOvAXvyeR9NOKIBK49u1K6XpxUN-50cJsxJPtaFzbpDaaz62KnUcvCk3z8e78unf9hhnJzP8xXSspA_1hJ2pXcmdvh7ZKrnXd-ibLe5sKrXmkNwMvN7zcL1WL19ZKbjhZmQux_nJzwwGzzaRQYolYT_F5WQJKfwyAFwFLUGZfBgP5ev7izDFvsn-fyYk6sRlQBCBLMp-jrOSt6W5o626Wo-0bsrWP2EmwUO1KNPVg2byYA2kO8uT2HmDLEVCj5T4cP00r7TmJswZ3_HRFHhne4i5JMpEJBRk2BMdjKgASDbbb92FavPaYCB2L29ZTCnimGbs5P2JMDImOOR2AUFNQJmre7uzDKhDlZEimQ5PQsQbhl90NBlRmMRxDzMFvr_82T4LXshXZ9mRpxMpHoh7PIyp0VW0CDuslkALgYct1mFuSIvJ1ofDYvW59UQFOu5e-9bFrMOnWqvN4n9m28bl3TGaUuR2KkMwIksBSwCq49fI9Wolxd8DDvipCXNtZPYgodF3wXf2IG40C0ETZt4WfJzkCmxCzxfhSsgrrd4pTOfDXv3W3vh3j7EtmUS4-cZh33up1mv2_fyyx_CUIzG2jCQIiKs1C765QuJ-uwIE30p-TZ7cvhbOvdzMDBWGcqzmeN-z1tAt0tFHaf7JjBcFfeatfl_Au5QRHph11QiyegB6XInFZBfHcPc6MUCIxVWotB7ueYNO9bsWaPuCDUuVu5FdcLTUVf9bXQBzgEaBOQrLaS-R2og_JcbdPNdVLuGZADtRjkkroX8vDne87wO1StoQcNp11zivouTwYfw7R2BCpBUhR5H8FICIEn1CygIdV1LAaT_eJZuXEmki-cllRinUA2tw2cvdeo0W2ZM8J8x0Q2ihkMd43W_E5_Q1ivcCjH-MevLZRuHlTmmgOBW4yttqsd628itcx6FkU0m4ypGwY2BZRBw_Z8p3gatoNeQ5-bv0GgBCMFJgg2Oz97x9JS-pHTV3VPNAITp4j2LasOzs6057A-iXdYQxPlag3_dR8th0ern-HQ0ToWrypM-4-6XjeaNEed_CIXrsbJ_rCy27GnJZbwZhDW4gAtq_nL3Tx3S2-F1A3QTUCPUOCIGIhz90k1A7-wDBmkCLQmqtiLBfNeUiDcIEUMykDs_drTWccnjXTz2W2nr0SPQm9A4b7UzoTsWe1InatN6BqVH0BU_8NgnqG60Cpvstxiv22ttrRekU9dOUnzZX9AV5xKDjLiPRWpizUCVAauilV3EZtu9b_uIn_ptv">
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cZone: 'whmcs.domainnameapi.com',
            cType: 'managed',
            cNounce: '71492',
            cRay: '7a08455e8f94d943',
            cHash: '9b14ccd9590a0d6',
            cUPMDTk: "\/DomainApi.svc?__cf_chl_tk=K_Tz4ugFY7fgg4N1w48OjuGaMfp3TpcSGJD6pziIrSI-1677577983-0-gaNycGzNCOU",
            cFPWv: 'g',
            cTTimeMs: '1000',
            cMTimeMs: '0',
            cTplV: 4,
            cTplB: 'cf',
            cRq: {
                ru: 'aHR0cHM6Ly93aG1jcy5kb21haW5uYW1lYXBpLmNvbS9Eb21haW5BcGkuc3Zj',
                ra: 'Y3VybC83LjY4LjA=',
                rm: 'R0VU',
                d: 'FueoFCP2/2mO5OSgu2iDCgaw2WosYoGj7QWlD9R+QZUbGEiHdXvLJXnrtVm6sUbmQu/b4QsEq8ZDiDldK6k/IGGHn1TJZVeL87QUXMqTTJfFGyQ4LzYA0abuCU4z9LT4RHQXmaZb6sgtULQFr5CDNmDGF5CB70lauWPEoKTgU6NvQLxAcsfRyhtZls2nBzpE9X+lJSPzD+nHFRFhp08YuTvA8Fv0d7GObxCkJQkCh18Dgz3ukIX+7u3YmkOnTO5vmkGvELRWr7jtOuINraBKWRgiKwqP/4Mp/mRuMz2nb4lCEYyQwZOU7xx3Jh09OXFzCMGttSkOv59gixnhcowHNuZ82HNrAF6BBF94Lnb6kLD6xFBX3yn5ySsM8Quq4Xh6LEt8BXCU9vEp2/xGGrPZOb7E9sTRgDdY97tIF4IWX9DlYyW9eU2b4sB0f+gp2TxhyjXDjOmaqZEQsuTalnUBbnWCYsf5iZ5vSy5JUIuxsJlkMb3cXWO3xNR4veAURNeNDL0MQcKp5tTzVsQOGWHlAUZ6AoCCOxhTSlh081Ldax3SKsa4DwStat8u2ttL/GQudkdCSxjvI6lv7bKPEqu9p9+FxO1lzw/oaTIr296hpfEvXCdz1AmY1ARVzZEVWLauHpaIYO/tEI0hn2CnPfUCvP+3TnUkvcv3ej9w0rBTnG7YCfMNQ3Q10qtunfRuIHVl',
                t: 'MTY3NzU3Nzk4My43ODEwMDA=',
                m: 'f6wC96AS1FLDVgpAX8CgDjpAt+NZg2eVypbqq8jVuOQ=',
                i1: 'ZqFuWZC6A62ehvpLLeUsBQ==',
                i2: 'llua4uFHxfHQ5bPr6gPryw==',
                zh: 'ylXpMcaZbEaQ5W8R+uRnC0ufxe2F7AhP9pWTMza+VHM=',
                uh: 'LgBfwTjckPmPFLl2OGGaoWOKkjIgTojK2wwoWSzqSQw=',
                hh: 'K/olDFbQ/sLilO3be5u4n3vke6PsmqHKbtULwbfaLTs=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/managed/js/transparent.gif?ray=7a08455e8f94d943');
        trkjs.setAttribute('alt', '');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/managed/v1?ray=7a08455e8f94d943';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/DomainApi.svc?__cf_chl_rt_tk=K_Tz4ugFY7fgg4N1w48OjuGaMfp3TpcSGJD6pziIrSI-1677577983-0-gaNycGzNCOU" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>


    <div class="footer" role="contentinfo">
        <div class="footer-inner">
            <div class="clearfix diagnostic-wrapper">
                <div class="ray-id">Ray ID: <code>7a08455e8f94d943</code></div>
            </div>
            <div class="text-center" id="footer-text">Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=challenge&utm_campaign=m" target="_blank">Cloudflare</a></div>
        </div>
    </div>
</body>
</html>
* Connection #0 to host whmcs.domainnameapi.com left intact

**Comment by ncti** [comment]
Hello,
Does the problem persist?

**Comment by muratgaygusuz** [comment]
Same error with our WHMCS 8.6.1 with PHP 7.4.

**Comment by bakcay** [comment]
Hello @muratgaygusuz , still the problem persist?

**Comment by muratgaygusuz** [comment]
> Hello @muratgaygusuz , still the problem persist?

It seems it's working now. but on whmcs domain page there are new fields and current state shows "TimeOut" value. It shows remaning days correctly. I'm not sure if it's correct or not. Just for your information. Thanks.

**Comment by bakcay** [comment]
> > Hello @muratgaygusuz , still the problem persist?
> 
> It seems it's working now.

Thank you, @domainreseller  network team verified. 
Thanks for collabrating
Closing issue
